<?php

namespace BlogBundle\Entity\Blog;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. (Et non j'ai C/P ! Mal)
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

}
