blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_pageX:
    path:     /page/{value}
    defaults: { _controller: BlogBundle:Blog:pageX }

blog_afficheOnePost:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Blog:displayPost }

blog_AddPost:
    path:     /admin/add
    defaults: { _controller: BlogBundle:Blog:addPost }

blog_EditPost:
    path:     /admin/Edit/{id}
    defaults: { _controller: BlogBundle:Blog:editPost }

blog_DeletePost:
    path:     /admin/Delete/{id}
    defaults: { _controller: BlogBundle:Blog:deletePost }

blog_addAdmin:
    path:     /admin/addAdmin
    defaults: { _controller: BlogBundle:Blog:addAdmin }

blog_EditComment:
    path:     /admin/EditComment/{id}
    defaults: { _controller: BlogBundle:Blog:editComment }

blog_DeleteComment:
    path:     /admin/DeleteComment/{idP}/{id}
    defaults: { _controller: BlogBundle:Blog:deleteComment }